// Edge TTS 音色目录，键为 info.ts 中 Language 的取值，每个语言的第一项即该语言的默认音色。
// 同一语言可以列出其他地区的发音人（例如英语包含 en-GB、en-AU），音色名称本身带有区域信息，
// 合成时会据此推导 SSML 的 xml:lang，因此跨区域选择也能正常朗读。
export const voiceOptions: Record<string, string[]> = {
    'zh-CN': [
        'zh-CN-XiaoxiaoNeural',
        'zh-CN-XiaoyiNeural',
        'zh-CN-YunxiNeural',
        'zh-CN-YunxiaNeural',
        'zh-CN-YunjianNeural',
        'zh-CN-YunyangNeural',
        'zh-CN-liaoning-XiaobeiNeural',
        'zh-CN-shaanxi-XiaoniNeural',
        'zh-TW-HsiaoChenNeural',
        'zh-TW-HsiaoYuNeural',
        'zh-TW-YunJheNeural',
        'zh-HK-HiuMaanNeural',
        'zh-HK-HiuGaaiNeural',
        'zh-HK-WanLungNeural',
    ],
    'zh-TW': [
        'zh-CN-XiaoxiaoNeural',
        'zh-CN-XiaoyiNeural',
        'zh-CN-YunxiNeural',
        'zh-CN-YunxiaNeural',
        'zh-CN-YunjianNeural',
        'zh-CN-YunyangNeural',
        'zh-CN-liaoning-XiaobeiNeural',
        'zh-CN-shaanxi-XiaoniNeural',
        'zh-TW-HsiaoChenNeural',
        'zh-TW-HsiaoYuNeural',
        'zh-TW-YunJheNeural',
        'zh-HK-HiuMaanNeural',
        'zh-HK-HiuGaaiNeural',
        'zh-HK-WanLungNeural',
    ],
    'en-US': [
        'en-US-AriaNeural',
        'en-US-JennyNeural',
        'en-US-MichelleNeural',
        'en-US-AnaNeural',
        'en-US-GuyNeural',
        'en-US-ChristopherNeural',
        'en-US-EricNeural',
        'en-US-RogerNeural',
        'en-US-SteffanNeural',
        'en-GB-SoniaNeural',
        'en-GB-LibbyNeural',
        'en-GB-MaisieNeural',
        'en-GB-RyanNeural',
        'en-GB-ThomasNeural',
        'en-AU-NatashaNeural',
        'en-AU-WilliamMultilingualNeural',
        'en-CA-ClaraNeural',
        'en-CA-LiamNeural',
        'en-IN-NeerjaNeural',
        'en-IN-PrabhatNeural',
        'en-IE-EmilyNeural',
        'en-IE-ConnorNeural',
        'en-HK-YanNeural',
        'en-HK-SamNeural',
        'en-NZ-MollyNeural',
        'en-NZ-MitchellNeural',
        'en-SG-LunaNeural',
        'en-SG-WayneNeural',
        'en-ZA-LeahNeural',
        'en-ZA-LukeNeural',
    ],
    'ja-JP': ['ja-JP-NanamiNeural', 'ja-JP-KeitaNeural'],
    'ko-KR': ['ko-KR-SunHiNeural', 'ko-KR-InJoonNeural'],
    'fr-FR': [
        'fr-FR-DeniseNeural',
        'fr-FR-EloiseNeural',
        'fr-FR-HenriNeural',
        'fr-CA-SylvieNeural',
        'fr-CA-AntoineNeural',
        'fr-CA-JeanNeural',
        'fr-BE-CharlineNeural',
        'fr-BE-GerardNeural',
        'fr-CH-ArianeNeural',
        'fr-CH-FabriceNeural',
    ],
    'es-ES': [
        'es-ES-ElviraNeural',
        'es-ES-AlvaroNeural',
        'es-MX-DaliaNeural',
        'es-MX-JorgeNeural',
        'es-AR-ElenaNeural',
        'es-AR-TomasNeural',
        'es-CO-SalomeNeural',
        'es-CO-GonzaloNeural',
        'es-US-PalomaNeural',
        'es-US-AlonsoNeural',
    ],
    'ru-RU': ['ru-RU-SvetlanaNeural', 'ru-RU-DmitryNeural'],
    'de-DE': [
        'de-DE-KatjaNeural',
        'de-DE-AmalaNeural',
        'de-DE-ConradNeural',
        'de-DE-KillianNeural',
        'de-AT-IngridNeural',
        'de-AT-JonasNeural',
        'de-CH-LeniNeural',
        'de-CH-JanNeural',
    ],
    'it-IT': ['it-IT-ElsaNeural', 'it-IT-IsabellaNeural', 'it-IT-DiegoNeural'],
    'tr-TR': ['tr-TR-EmelNeural', 'tr-TR-AhmetNeural'],
    'pt-PT': ['pt-PT-RaquelNeural', 'pt-PT-DuarteNeural'],
    'pt-BR': ['pt-BR-FranciscaNeural', 'pt-BR-AntonioNeural'],
    'vi-VN': ['vi-VN-HoaiMyNeural', 'vi-VN-NamMinhNeural'],
    'id-ID': ['id-ID-GadisNeural', 'id-ID-ArdiNeural'],
    'th-TH': ['th-TH-PremwadeeNeural', 'th-TH-NiwatNeural'],
    'ms-MY': ['ms-MY-YasminNeural', 'ms-MY-OsmanNeural'],
    'ar-SA': [
        'ar-SA-ZariyahNeural',
        'ar-SA-HamedNeural',
        'ar-EG-SalmaNeural',
        'ar-EG-ShakirNeural',
        'ar-AE-FatimaNeural',
        'ar-AE-HamdanNeural',
    ],
    'hi-IN': ['hi-IN-SwaraNeural', 'hi-IN-MadhurNeural'],
    'km-KH': ['km-KH-SreymomNeural', 'km-KH-PisethNeural'],
    'mn-MN': ['mn-MN-YesuiNeural', 'mn-MN-BataaNeural'],
    'nb-NO': ['nb-NO-PernilleNeural', 'nb-NO-FinnNeural'],
    'fa-IR': ['fa-IR-DilaraNeural', 'fa-IR-FaridNeural'],
    'sv-SE': ['sv-SE-SofieNeural', 'sv-SE-MattiasNeural'],
    'pl-PL': ['pl-PL-ZofiaNeural', 'pl-PL-MarekNeural'],
    'nl-NL': [
        'nl-NL-ColetteNeural',
        'nl-NL-FennaNeural',
        'nl-NL-MaartenNeural',
        'nl-BE-DenaNeural',
        'nl-BE-ArnaudNeural',
    ],
    'uk-UA': ['uk-UA-PolinaNeural', 'uk-UA-OstapNeural'],
    'he-IL': ['he-IL-HilaNeural', 'he-IL-AvriNeural'],
};

// 未配置音色时使用的默认发音人
export function getDefaultVoice(locale: string): string | undefined {
    return voiceOptions[locale]?.[0];
}

// 下拉列表中的显示名，去掉统一的 Neural 后缀，保留区域前缀以便区分同名发音人
export function getVoiceLabel(voice: string): string {
    return voice.replace(/Neural$/, '');
}
